### ISSUE TITLE
Allow Submission of Employee Details Without Email & Add Default Profile Pictures

### ISSUE THREAD

**Issue by PublisherName** [PublisherName/Digital-Citizen-Charter-Api#4]
## Issue

Some employee emails are not available, making it difficult to submit their details through the system.

## ToDo

- [x] Submission Without Email: Modify the employee details submission form to allow submission even if the employee's email is not available.

- [ ] Default Profile Pictures: Implement a feature to set default profile pictures for employees who do not upload their own profile pictures.

- [x] Add Description Field: Include a description field in the employee profile to provide additional information, particularly useful for identifying the ward chairpersons and determining their respective wards.

**Comment by PublisherName** [comment]
#11 has added the description field in the employee profile.
